/**
 * THE COMPARATOR CLASS: its netlist, its symbol and its conformance rig.
 *
 * ## What a comparator model is for, and what it must therefore reproduce
 *
 * A comparator is a decision, not an amplifier. Its output is at one rail or the
 * other and the only interesting questions are WHEN it flips and HOW LONG it
 * takes. So the topology is an offset source, a decision, and a delay:
 *
 *   OUT = low  while  V(IN+) - V(IN-) < offset
 *   OUT = high otherwise
 *   ...arriving `propagationDelay` after the input crossed
 *
 * The delay is not decoration. It is why anyone simulates a comparator rather
 * than writing `if` in their head, and it is the number every comparator
 * datasheet states and no amplifier datasheet does.
 *
 * ## Open collector, which is what the document says it is
 *
 * A part that states a SATURATION VOLTAGE and an OUTPUT SINK CURRENT has an
 * open-collector or open-drain output: it pulls down and it does not pull up.
 * Modelling it as push-pull would hand the user a part that drives a rail the
 * real one leaves floating, which is a wrong answer delivered confidently.
 *
 * Where the datasheet states neither, the output is emitted as push-pull and the
 * header says so. That is a generator topology choice, not a reading: a stated
 * saturation voltage is positive evidence of a pull-down-only stage, while its
 * absence proves nothing. The release assurance therefore flags this choice for
 * review instead of silently presenting it as a fact about the part.
 *
 * ## The delay is a transmission line, and the reason is portability
 *
 * `E` sources with a delay are not written the same way in ngspice and LTspice,
 * and a file verified only under ngspice can be one the customer's tool refuses:
 * that is the `bench:kicad` lesson. A lossless transmission line is plain SPICE
 * and is spelled identically in both. It is terminated in its own impedance, so
 * there are no reflections, and the halving that a matched termination causes is
 * undone by a gain of two.
 */

import { toSpice } from "./units";
import { citationLines, spiceName } from "./emit";
import { COMPARATOR, supportedCorners, usableAt, valueAt, type ModelBlock, type ModelParameter } from "./model";
import { ngspiceFailureReason, runNgspice, TOLERANCE_PCT, type Check, type ConformanceReport } from "./verify";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** The `.subckt` port order, the `.asy` pin order and nothing else. */
export const COMPARATOR_TERMINALS = ["IN+", "IN-", "OUT", "VCC", "GND"] as const;

export const COMPARATOR_TOPOLOGY =
  "behavioural comparator (offset source, a rail-to-rail decision, and the datasheet's own propagation delay as a matched transmission line)";

const CORNER_INDEX: Record<"typ" | "min" | "max", number> = { typ: 1, min: 2, max: 3 };

function cornerExpression(block: ModelBlock, parameter: ModelParameter, corners: Array<"typ" | "min" | "max">): string | null {
  const terms: string[] = [];
  for (const corner of corners) {
    const value = valueAt(block, parameter, corner);
    if (value === null) return null;
    terms.push(`(CORNER==${CORNER_INDEX[corner]})*${toSpice(value)}`);
  }
  return terms.join(" + ");
}

/**
 * Does the document say this output only pulls DOWN?
 *
 * A stated saturation voltage or sink current is what an open-collector part
 * prints, because those are the only two numbers that describe a stage which
 * cannot source. Reject-on-proof in reverse: presence is the evidence, and
 * absence means the simpler push-pull stage and a line in the header saying so.
 */
export function isOpenCollector(block: ModelBlock): boolean {
  const corners = supportedCorners(block, COMPARATOR);
  return usableAt(block, "outputLowVoltage", corners) || usableAt(block, "outputSinkCurrent", corners);
}

export function emitComparatorSubckt(block: ModelBlock, options: { partNumber: string; datasheet?: string }): string {
  const corners = supportedCorners(block, COMPARATOR);
  const name = spiceName(options.partNumber);
  const has = (p: ModelParameter) => usableAt(block, p, corners);
  const openCollector = isOpenCollector(block);
  const lines: string[] = [];

  lines.push(`* ${name} behavioural SPICE model, generated by Forge.`);
  lines.push("*");
  lines.push(`* Topology: ${COMPARATOR_TOPOLOGY}.`);
  lines.push("* The topology is a constant of the generator and is not read from the");
  // NOT "every parameter below is read from the datasheet", which stopped being
  // true the day a user could supply one. Each line says where it came from and
  // a supplied value says so in words; the preamble points at that rather than
  // making a blanket claim it cannot keep.
  lines.push("* document. Every PARAMETER below says where it came from.");
  lines.push("*");
  if (options.datasheet) lines.push(`* Datasheet: ${options.datasheet}`);
  if (block.scope) lines.push(`* Specification block: ${block.scope}`);
  if (block.group) lines.push(`* Grade: ${block.group}`);
  lines.push("*");
  lines.push(...citationLines(block, has, 20));
  lines.push("*");
  lines.push(
    openCollector
      ? "* OPEN-COLLECTOR OUTPUT. This datasheet states a saturation voltage or a"
      : "* PUSH-PULL OUTPUT ASSUMPTION — REVIEW REQUIRED. This datasheet states neither a saturation voltage nor"
  );
  lines.push(
    openCollector
      ? "* sink current, which only a stage that pulls down and does not pull up has."
      : "* a sink current, so Forge could not establish the output stage from these parameters. The output"
  );
  lines.push(
    openCollector
      ? "* OUT is pulled low and released; YOUR CIRCUIT MUST SUPPLY THE PULL-UP."
      : "* is driven both ways as a disclosed generator topology. If your part is open-collector, this model drives high"
  );
  if (!openCollector) lines.push("* where the real one floats.");
  const absent = (["offsetVoltage", "hysteresis", "quiescentCurrent"] as ModelParameter[]).filter((p) => !has(p));
  if (absent.length > 0) {
    lines.push("*");
    lines.push(`* NOT MODELLED, because the datasheet does not state them: ${absent.join(", ")}.`);
    lines.push("* Nothing is assumed in their place. The model does not reproduce them.");
  }
  lines.push("*");
  if (corners.length > 1) {
    const highest = Math.max(...corners.map((c) => CORNER_INDEX[c]));
    lines.push(`* Corners: ${corners.map((c) => `${CORNER_INDEX[c]}=${c}`).join(", ")}. Default is typical.`);
    lines.push("*     .param CORNER=1");
    lines.push(`*     .step param CORNER 1 ${highest} 1`);
    lines.push(`* and instantiate as:  Xu1 ${COMPARATOR_TERMINALS.join(" ")} ${name} CORNER={CORNER}`);
  }
  lines.push("");

  lines.push(`.subckt ${name} ${COMPARATOR_TERMINALS.join(" ")} CORNER=1`);
  for (const parameter of Object.keys(block.values) as ModelParameter[]) {
    if (!has(parameter)) continue;
    const expression = cornerExpression(block, parameter, corners);
    if (expression) lines.push(`.param ${parameter}={${expression}}`);
  }

  const inputNode = has("offsetVoltage") ? "ninp" : "IN+";
  if (has("offsetVoltage")) lines.push("Vos ninp IN+ {offsetVoltage}");

  // THE DECISION, as a rail-to-rail step with hysteresis where the document
  // states it. `tanh` over a narrow band rather than a ternary: a discontinuity
  // is what makes a transient analysis fail to converge, and the band is far
  // narrower than any offset this model carries.
  const band = has("hysteresis") ? "{hysteresis}" : "1e-6";
  lines.push(`.param VDEC=1`);
  lines.push(`Bdec ndec 0 V={VDEC}*(0.5+0.5*tanh(V(${inputNode},IN-)/${band}))`);

  // THE DELAY. Plain SPICE, spelled the same in ngspice and LTspice, terminated
  // in its own impedance so nothing reflects.
  //
  // NO GAIN OF TWO. A matched termination halves the step only when the SOURCE
  // has a series impedance of Z0; here the line is driven by an ideal behavioural
  // source, so the far end sees the full amplitude. Doubling it drove the output
  // factor below zero and the stage became a negative resistance holding OUT at
  // its saturation voltage forever - a model that simulated cleanly, produced no
  // transition at all, and would have been shipped by any check that only asked
  // whether the file parses.
  lines.push(".param ZDLY=1e3");
  lines.push("Tdly ndec 0 ndly 0 Z0={ZDLY} TD={propagationDelay}");
  lines.push("Rterm ndly 0 {ZDLY}");

  if (openCollector) {
    // Pulls DOWN to the stated saturation voltage and RELEASES. A very large
    // resistance to the rail is not a pull-up: it is the leakage path, and it is
    // what leaves the node floating for the user's own pull-up to define.
    const low = has("outputLowVoltage") ? "{outputLowVoltage}" : "0";
    // Clamped into [0,1] so no arithmetic anywhere upstream can turn the
    // pull-down into a source. See the note on the gain of two above.
    //
    // `max(0,min(1,x))` AND NOT `limit(x,0,1)`. ngspice accepts `limit` in a
    // B-source expression, evaluates it to something else, and reports nothing:
    // the pull-down stayed on, the output never left its saturation voltage, and
    // the model simulated perfectly cleanly while doing nothing at all. Found by
    // running the deck by hand. `min` and `max` are plain SPICE and mean the
    // same thing in both tools.
    lines.push(`Bout OUT GND I=max(0,min(1,1 - V(ndly)/{VDEC}))*(V(OUT,GND) - ${low})/1e-3`);
    lines.push("Roff OUT GND 1e9");
  } else {
    lines.push("Bout OUT GND V=V(VCC,GND)*max(0,min(1,V(ndly)/{VDEC}))");
  }
  if (has("quiescentCurrent")) lines.push("Biq VCC GND I={quiescentCurrent}");
  lines.push(".ends");
  lines.push("");
  return lines.join("\n");
}

/** The LTspice symbol. Pin order derives from `COMPARATOR_TERMINALS`. */
export function emitComparatorAsy(partNumber: string): string {
  const name = spiceName(partNumber);
  const geometry: Record<(typeof COMPARATOR_TERMINALS)[number], { x: number; y: number; label: string }> = {
    "IN+": { x: -32, y: -32, label: "LEFT" },
    "IN-": { x: -32, y: 32, label: "LEFT" },
    OUT: { x: 32, y: 0, label: "RIGHT" },
    VCC: { x: 0, y: -32, label: "TOP" },
    GND: { x: 0, y: 32, label: "BOTTOM" }
  };
  const lines = [
    "Version 4",
    "SymbolType CELL",
    "LINE Normal -32 -48 -32 48",
    "LINE Normal -32 48 32 0",
    "LINE Normal 32 0 -32 -48",
    "WINDOW 0 16 -32 Left 2",
    "WINDOW 3 16 32 Left 2",
    "SYMATTR Prefix X",
    `SYMATTR Value ${name}`,
    `SYMATTR SpiceModel ${name}`,
    `SYMATTR Description ${name} behavioural comparator generated by Forge`
  ];
  COMPARATOR_TERMINALS.forEach((terminal, index) => {
    const spot = geometry[terminal];
    lines.push(`PIN ${spot.x} ${spot.y} ${spot.label} 8`);
    lines.push(`PINATTR PinName ${terminal}`);
    lines.push(`PINATTR SpiceOrder ${index + 1}`);
  });
  return lines.join("\n") + "\n";
}

function parse(output: string, pattern: RegExp): number | null {
  const match = output.match(pattern);
  if (!match) return null;
  const value = Number.parseFloat(match[1]);
  return Number.isFinite(value) ? value : null;
}

/**
 * The conformance deck: a step in, and the time the output takes to answer.
 *
 * This is the one measurement a comparator exists for, and unlike the
 * amplifier's slew rate it needs nothing the datasheet does not print: a step
 * that crosses the threshold, and the moment the output passes half way.
 */
function deck(subckt: string, name: string, corner: number, delaySeconds: number, supply: number): string {
  const step = delaySeconds / 10;
  const stop = delaySeconds * 4 + step * 4;
  return [
    `* Forge conformance deck for ${name}, corner ${corner}`,
    subckt,
    `Xc inp 0 out vcc 0 ${name} CORNER=${corner}`,
    // A pull-up, because an open-collector output has nothing to drive high with
    // and the model is deliberately faithful about that.
    `Rpull vcc out 10k`,
    `Vcc vcc 0 DC ${toSpice(supply)}`,
    // Well past any offset this part states, so the crossing is unambiguous.
    `Vin inp 0 PULSE(${toSpice(-supply / 4)} ${toSpice(supply / 4)} ${toSpice(step)} 1e-12 1e-12 ${toSpice(stop)} ${toSpice(stop * 2)})`,
    ".control",
    `tran ${toSpice(delaySeconds / 200)} ${toSpice(stop)}`,
    // The output crossing half the supply, measured FROM the input edge.
    `meas tran t_out WHEN v(out)=${toSpice(supply / 2)} RISE=1`,
    ".endc",
    ".end",
    ""
  ].join("\n");
}

/** What a generic transient rig can measure on a comparator. */
const MEASURABLE: ModelParameter[] = ["propagationDelay"];

/**
 * Runs the comparator model and compares it against the values it was built
 * from. Never throws.
 */
export async function verifyComparator(
  subckt: string,
  block: ModelBlock,
  partNumber: string,
  corners: Array<"typ" | "min" | "max">
): Promise<ConformanceReport> {
  const name = spiceName(partNumber);
  const checks: Check[] = [];
  const directory = await mkdtemp(join(tmpdir(), "forge-spice-cmp-"));
  let simulatorMissing = false;

  const unverifiable = (parameter: ModelParameter, corner: "typ" | "min" | "max", reason: string) => {
    if (!usableAt(block, parameter, corners)) return;
    const expected = valueAt(block, parameter, corner);
    if (expected !== null) checks.push({ parameter, corner, expected, measured: null, verdict: "unverifiable", reason, errorPct: null });
  };

  try {
    for (const corner of corners) {
      const delay = valueAt(block, "propagationDelay", corner);
      if (delay === null || delay <= 0) continue;
      // The supply the datasheet states, where it states one. A comparator's
      // decision does not depend on it, so this is a probe point rather than a
      // modelling choice, and 5 V is the ordinary bench value where the document
      // is silent.
      const supply = valueAt(block, "supplyVoltage", corner) ?? 5;

      const file = join(directory, `${name}-${corner}.cir`);
      await writeFile(file, deck(subckt, name, CORNER_INDEX[corner], delay, supply), "utf8");
      const { stdout, ok, failure } = await runNgspice(file);
      if (!ok) {
        simulatorMissing ||= failure === "missing";
        for (const parameter of MEASURABLE) unverifiable(parameter, corner, ngspiceFailureReason(failure));
        continue;
      }

      // The input edge is at `delay / 10`; the answer is what comes after it.
      const crossed = parse(stdout, /t_out\s*=\s*([-\d.eE+]+)/);
      const measured = crossed === null ? null : crossed - delay / 10;
      if (measured === null) {
        unverifiable("propagationDelay", corner, "the simulation produced no output transition to measure");
        continue;
      }
      const expected = delay;
      const errorPct = Math.abs((measured - expected) / expected) * 100;
      checks.push({
        parameter: "propagationDelay",
        corner,
        expected,
        measured,
        verdict: errorPct <= TOLERANCE_PCT ? "pass" : "fail",
        reason: errorPct <= TOLERANCE_PCT ? undefined : `measured ${measured.toPrecision(4)} against a stated ${expected.toPrecision(4)}`,
        errorPct
      });

      // Read and not simulated. An input offset shifts the threshold, which this
      // rig crosses far too fast to resolve, and reporting a number it cannot
      // measure would be worse than saying so.
      for (const parameter of ["offsetVoltage", "hysteresis", "outputLowVoltage", "outputSinkCurrent"] as ModelParameter[]) {
        unverifiable(parameter, corner, "this generic rig measures the decision's timing; the datasheet states no test circuit for the rest");
      }
    }
  } finally {
    await rm(directory, { recursive: true, force: true }).catch(() => {});
  }

  return { checks, simulatorMissing };
}
