/**
 * Instrumentation-amplifier model driven by the gain law printed in the
 * datasheet. The numerator is evidence, not a family default.
 */

import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { citationLines, spiceName } from "./emit";
import { INSTRUMENTATION, supportedCorners, usableAt, valueAt, type ModelBlock, type ModelParameter } from "./model";
import { ngspiceFailureReason, runNgspice, TOLERANCE_PCT, type Check, type ConformanceReport } from "./verify";
import { toSpice } from "./units";

export const INSTRUMENTATION_TERMINALS = ["IN+", "IN-", "OUT", "REF", "VCC", "VEE", "RG+", "RG-"] as const;

export const INSTRUMENTATION_TOPOLOGY =
  "behavioural instrumentation amplifier whose external gain resistor is interpreted by the datasheet's printed G = 1 + K/RG law";

const CORNER_INDEX: Record<"typ" | "min" | "max", number> = { typ: 1, min: 2, max: 3 };

function cornerExpression(block: ModelBlock, parameter: ModelParameter, corners: Array<"typ" | "min" | "max">): string | null {
  const terms: string[] = [];
  for (const corner of corners) {
    const value = valueAt(block, parameter, corner);
    if (value === null) return null;
    terms.push(`(CORNER==${CORNER_INDEX[corner]})*${toSpice(value)}`);
  }
  return terms.join(" + ");
}

export function emitInstrumentationSubckt(block: ModelBlock, options: { partNumber: string; datasheet?: string }): string {
  const corners = supportedCorners(block, INSTRUMENTATION);
  const name = spiceName(options.partNumber);
  const has = (parameter: ModelParameter) => usableAt(block, parameter, corners);
  const lines = [
    `* ${name} behavioural SPICE model, generated by Forge.`,
    "*",
    `* Topology: ${INSTRUMENTATION_TOPOLOGY}.`,
    "* The topology is a constant of the generator and is not read from the",
    "* document. Every parameter below says where it came from; the gain",
    "* numerator is read from the printed equation.",
    "*",
    ...(options.datasheet ? [`* Datasheet: ${options.datasheet}`] : []),
    ...(block.scope ? [`* Specification block: ${block.scope}`] : []),
    ...(block.group ? [`* Grade: ${block.group}`] : []),
    ...citationLines(block, has, 20),
    "*",
    "* NOT MODELLED unless a future evidence-backed topology adds them: bandwidth,",
    "* slew rate, noise, CMRR, input/output limits, clipping and protection.",
    "* Nothing is assumed in their place; this is a DC gain/offset model.",
    ""
  ];
  if (corners.length > 1) {
    const highest = Math.max(...corners.map((corner) => CORNER_INDEX[corner]));
    lines.push(`* Corners: ${corners.map((corner) => `${CORNER_INDEX[corner]}=${corner}`).join(", ")}. Default is typical.`);
    lines.push("* To sweep them, define CORNER and pass CORNER={CORNER} to the instance.");
    lines.push(`* Valid values are 1 through ${highest}.`);
    lines.push("");
  }
  lines.push(`.subckt ${name} ${INSTRUMENTATION_TERMINALS.join(" ")} CORNER=1`);
  for (const parameter of Object.keys(block.values) as ModelParameter[]) {
    if (!has(parameter)) continue;
    const expression = cornerExpression(block, parameter, corners);
    if (expression) lines.push(`.param ${parameter}={${expression}}`);
  }
  // A one-volt sensing source makes abs(I(Vrg)) equal 1/RG. It lives only on
  // the programming pins and therefore neither loads nor alters either input.
  lines.push("Vrg RG+ RG- 1");
  const offset = has("offsetVoltage") ? "+{offsetVoltage}" : "";
  lines.push(`Bout OUT REF V=(V(IN+,IN-)${offset})*(1+{gainResistance}*abs(I(Vrg)))`);
  if (has("quiescentCurrent")) lines.push("Biq VCC VEE I={quiescentCurrent}");
  lines.push(`.ends ${name}`);
  lines.push("");
  return lines.join("\n");
}

export function emitInstrumentationAsy(partNumber: string): string {
  const name = spiceName(partNumber);
  const positions: Record<(typeof INSTRUMENTATION_TERMINALS)[number], [number, number, "RIGHT" | "LEFT"]> = {
    "IN+": [0, 48, "RIGHT"], "IN-": [0, 80, "RIGHT"], "RG+": [0, 128, "RIGHT"], "RG-": [0, 160, "RIGHT"],
    OUT: [224, 64, "LEFT"], REF: [224, 112, "LEFT"], VCC: [96, 0, "RIGHT"], VEE: [96, 208, "LEFT"]
  };
  const lines = [
    "Version 4", "SymbolType CELL", "RECTANGLE Normal 32 16 192 192", "TEXT 112 88 Center 0 INA",
    "SYMATTR Prefix X", `SYMATTR Value ${name}`, `SYMATTR SpiceModel ${name}`
  ];
  INSTRUMENTATION_TERMINALS.forEach((terminal, index) => {
    const [x, y, direction] = positions[terminal];
    lines.push(`PIN ${x} ${y} ${direction} 16`);
    lines.push(`PINATTR PinName ${terminal}`);
    lines.push(`PINATTR SpiceOrder ${index + 1}`);
  });
  return `${lines.join("\n")}\n`;
}

function parse(output: string, name: string): number | null {
  const match = output.match(new RegExp(`\\b${name}\\s*=\\s*([-\\d.eE+]+)`, "i"));
  const value = match ? Number.parseFloat(match[1]) : Number.NaN;
  return Number.isFinite(value) ? value : null;
}

function comparison(parameter: ModelParameter, corner: "typ" | "min" | "max", expected: number, measured: number | null): Check {
  if (measured === null) return { parameter, corner, expected, measured, verdict: "unverifiable", reason: "the simulation produced no value for this measurement", errorPct: null };
  const errorPct = expected === 0 ? (measured === 0 ? 0 : 100) : Math.abs((measured - expected) / expected) * 100;
  return { parameter, corner, expected, measured, verdict: errorPct <= TOLERANCE_PCT ? "pass" : "fail", reason: errorPct <= TOLERANCE_PCT ? undefined : `measured ${measured.toPrecision(4)} against a stated ${expected.toPrecision(4)}`, errorPct };
}

export async function verifyInstrumentation(
  subckt: string,
  block: ModelBlock,
  partNumber: string,
  corners: Array<"typ" | "min" | "max">
): Promise<ConformanceReport> {
  const name = spiceName(partNumber);
  const checks: Check[] = [];
  const directory = await mkdtemp(join(tmpdir(), "forge-spice-ina-"));
  let simulatorMissing = false;
  try {
    for (const corner of corners) {
      const numerator = valueAt(block, "gainResistance", corner);
      if (numerator === null) continue;
      const index = CORNER_INDEX[corner];
      const deck = [
        `* Forge instrumentation-amplifier conformance deck for ${name}`,
        subckt,
        `Xgain inp inn out 0 vcc vee rgp rgn ${name} CORNER=${index}`,
        `Rg rgp rgn ${toSpice(numerator)}`,
        "Vip inp 0 0.1", "Vin inn 0 0", "Vcc vcc 0 5", "Vee vee 0 -5",
        ".control", "op", "let measured_k=(v(out)/0.1-1)*" + toSpice(numerator), "print measured_k", "print v(out)", "print i(Vcc)", ".endc", ".end", ""
      ].join("\n");
      const file = join(directory, `${name}-${corner}.cir`);
      await writeFile(file, deck, "utf8");
      const result = await runNgspice(file);
      if (!result.ok) {
        simulatorMissing ||= result.failure === "missing";
        for (const parameter of ["gainResistance", "offsetVoltage", "quiescentCurrent"] as ModelParameter[]) {
          if (!usableAt(block, parameter, corners)) continue;
          const expected = valueAt(block, parameter, corner);
          if (expected !== null) checks.push({ parameter, corner, expected, measured: null, verdict: "unverifiable", reason: ngspiceFailureReason(result.failure), errorPct: null });
        }
        continue;
      }
      checks.push(comparison("gainResistance", corner, numerator, parse(result.stdout, "measured_k")));
      if (usableAt(block, "offsetVoltage", corners)) {
        const expected = valueAt(block, "offsetVoltage", corner);
        const output = parse(result.stdout, "v\\(out\\)");
        if (expected !== null) checks.push(comparison("offsetVoltage", corner, expected, output === null ? null : output / 2 - 0.1));
      }
      if (usableAt(block, "quiescentCurrent", corners)) {
        const expected = valueAt(block, "quiescentCurrent", corner);
        const current = parse(result.stdout, "i\\(vcc\\)");
        if (expected !== null) checks.push(comparison("quiescentCurrent", corner, expected, current === null ? null : Math.abs(current)));
      }
    }
  } finally {
    await rm(directory, { recursive: true, force: true }).catch(() => {});
  }
  return { checks, simulatorMissing };
}
