/**
 * THE VOLTAGE REFERENCE CLASS: its netlist, its symbol and its conformance rig.
 *
 * ## The topology is the datasheet's own definitions, written as a circuit
 *
 * A reference datasheet does not describe a circuit, but it does state two
 * partial derivatives and it states them by name. REF5025 prints them beside
 * their own symbols:
 *
 *     dVOUT/dVIN     Line regulation    1 ppm/V
 *     dVOUT/dILOAD   Load regulation   20 ppm/mA
 *
 * A source whose value moves with the input at the stated slope, behind a
 * resistance equal to the stated output slope, IS those two statements. Nothing
 * is invented: the model reproduces exactly what the document promises and
 * nothing more. Where the document states neither, there is no model, because
 * an ideal source reproduces none of the vendor's promises while LOOKING like a
 * perfect part, which is worse than refusing.
 *
 * ## The line term needs an anchor, and the anchor is read, not chosen
 *
 * A slope has no absolute reference point. The output is anchored at the
 * MINIMUM SUPPLY the datasheet states, which is a value read off the same page,
 * and the file's header says so. Where no supply minimum was read, the line
 * term is omitted rather than anchored somewhere convenient.
 *
 * The choice is immaterial in size and is disclosed anyway: on REF5025 the
 * whole span from 3.25 V to 18 V moves the output by 15 ppm.
 */

import { toSpice } from "./units";
import { citationLines, spiceName } from "./emit";
import { REFERENCE, supportedCorners, usableAt, valueAt, type ModelBlock, type ModelParameter } from "./model";
import { runNgspice, TOLERANCE_PCT, type Check, type ConformanceReport } from "./verify";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** The `.subckt` port order, the `.asy` pin order and nothing else. */
export const REFERENCE_TERMINALS = ["IN", "OUT", "GND"] as const;

export const REFERENCE_TOPOLOGY =
  "behavioural voltage reference (nominal output, the datasheet's own line-regulation slope on the input, behind an output resistance equal to its load-regulation slope)";

const CORNER_INDEX: Record<"typ" | "min" | "max", number> = { typ: 1, min: 2, max: 3 };

function cornerExpression(block: ModelBlock, parameter: ModelParameter, corners: Array<"typ" | "min" | "max">): string | null {
  const terms: string[] = [];
  for (const corner of corners) {
    const value = valueAt(block, parameter, corner);
    if (value === null) return null;
    terms.push(`(CORNER==${CORNER_INDEX[corner]})*${toSpice(value)}`);
  }
  return terms.join(" + ");
}

/**
 * The supply the output is anchored at: the minimum the datasheet states.
 *
 * Null when the document states none, and the caller then emits no line term at
 * all rather than picking a voltage.
 */
export function anchorSupply(block: ModelBlock): number | null {
  const supply = block.values.supplyVoltage;
  if (!supply) return null;
  return supply.si.min ?? supply.si.typ ?? null;
}

export function emitReferenceSubckt(block: ModelBlock, options: { partNumber: string; datasheet?: string }): string {
  const corners = supportedCorners(block, REFERENCE);
  const name = spiceName(options.partNumber);
  const has = (p: ModelParameter) => usableAt(block, p, corners);
  const anchor = anchorSupply(block);
  const lines: string[] = [];

  lines.push(`* ${name} behavioural SPICE model, generated by Forge.`);
  lines.push("*");
  lines.push(`* Topology: ${REFERENCE_TOPOLOGY}.`);
  lines.push("* The topology is a constant of the generator and is not read from the");
  // NOT "every parameter below is read from the datasheet", which stopped being
  // true the day a user could supply one. Each line says where it came from and
  // a supplied value says so in words; the preamble points at that rather than
  // making a blanket claim it cannot keep.
  lines.push("* document. Every PARAMETER below says where it came from.");
  lines.push("*");
  if (options.datasheet) lines.push(`* Datasheet: ${options.datasheet}`);
  if (block.scope) lines.push(`* Specification block: ${block.scope}`);
  if (block.group) lines.push(`* Grade: ${block.group}`);
  lines.push("*");
  lines.push(...citationLines(block, has));

  const absent = (["lineRegulation", "loadRegulation", "outputDrift", "quiescentCurrent"] as ModelParameter[]).filter((p) => !has(p));
  if (absent.length > 0) {
    lines.push("*");
    lines.push(`* NOT MODELLED, because the datasheet does not state them: ${absent.join(", ")}.`);
    lines.push("* Nothing is assumed in their place. The model does not reproduce them.");
  }
  if (has("lineRegulation") && anchor === null) {
    lines.push("*");
    lines.push("* The line regulation was READ but is NOT modelled: a slope needs an");
    lines.push("* anchor, this datasheet states no minimum supply, and choosing one");
    lines.push("* would be this generator inventing an operating point.");
  }
  if (has("lineRegulation") && anchor !== null) {
    lines.push("*");
    lines.push(`* The output is anchored at VIN = ${anchor} V, the minimum supply this`);
    lines.push("* datasheet states, and moves from there at the stated line-regulation");
    lines.push("* slope. The anchor is read from the document, not chosen.");
  }
  lines.push("*");
  lines.push("* THE DRIFT IS NOT MODELLED. Temperature is not a node in this netlist,");
  lines.push("* and a reference's drift is stated per degree; it is on the record and");
  lines.push("* in the report so it can be used by hand.");
  lines.push("*");
  if (corners.length > 1) {
    const highest = Math.max(...corners.map((c) => CORNER_INDEX[c]));
    lines.push(`* Corners: ${corners.map((c) => `${CORNER_INDEX[c]}=${c}`).join(", ")}. Default is typical.`);
    lines.push("* To sweep them, add to your schematic:");
    lines.push("*     .param CORNER=1");
    lines.push(`*     .step param CORNER 1 ${highest} 1`);
    lines.push(`* and instantiate as:  Xu1 ${REFERENCE_TERMINALS.join(" ")} ${name} CORNER={CORNER}`);
  }
  lines.push("");

  // Every parameter local to the subcircuit, so two Forge models can sit in one
  // schematic. Declared globally, LTspice stops with a duplicate definition.
  lines.push(`.subckt ${name} ${REFERENCE_TERMINALS.join(" ")} CORNER=1`);
  for (const parameter of Object.keys(block.values) as ModelParameter[]) {
    if (!has(parameter)) continue;
    const expression = cornerExpression(block, parameter, corners);
    if (expression) lines.push(`.param ${parameter}={${expression}}`);
  }

  const lineTerm =
    has("lineRegulation") && anchor !== null
      ? `*(1 + {lineRegulation}*(V(IN,GND) - ${toSpice(anchor)}))`
      : "";
  // Brace the parameter, never the whole expression: LTspice rejects the latter
  // with "Questionable use of curly braces" while ngspice accepts both, so a
  // file verified only under ngspice can be one the customer's tool refuses.
  lines.push(`Bref nref GND V={outputVoltage}${lineTerm}`);

  if (has("loadRegulation")) {
    // Load regulation is a FRACTIONAL change per amp, so the resistance it
    // describes is that slope times the nominal output.
    lines.push(".param ROUT={outputVoltage*loadRegulation}");
    lines.push("Rout nref OUT {ROUT}");
  } else {
    // NO ELEMENT AT ALL, rather than a zero-ohm resistor. A datasheet stating
    // no load regulation has promised nothing about the output impedance, and
    // a zero-valued resistor is a claim of a perfect one as well as an element
    // some simulators warn on. A zero-volt source ties the nodes and is the
    // ordinary SPICE idiom for it.
    lines.push("Vout nref OUT 0");
  }
  if (has("quiescentCurrent")) lines.push("Biq IN GND I={quiescentCurrent}");
  lines.push(".ends");
  lines.push("");
  return lines.join("\n");
}

/** The LTspice symbol. Pin order derives from `REFERENCE_TERMINALS`. */
export function emitReferenceAsy(partNumber: string): string {
  const name = spiceName(partNumber);
  const geometry: Record<(typeof REFERENCE_TERMINALS)[number], { x: number; y: number; label: string }> = {
    IN: { x: -32, y: 0, label: "LEFT" },
    OUT: { x: 32, y: 0, label: "RIGHT" },
    GND: { x: 0, y: 32, label: "BOTTOM" }
  };
  const lines = [
    "Version 4",
    "SymbolType CELL",
    "RECTANGLE Normal -32 -32 32 32",
    "WINDOW 0 0 -40 Bottom 2",
    "WINDOW 3 0 40 Top 2",
    "SYMATTR Prefix X",
    `SYMATTR Value ${name}`,
    `SYMATTR SpiceModel ${name}`,
    `SYMATTR Description ${name} behavioural voltage reference generated by Forge`
  ];
  REFERENCE_TERMINALS.forEach((terminal, index) => {
    const spot = geometry[terminal];
    lines.push(`PIN ${spot.x} ${spot.y} ${spot.label} 8`);
    lines.push(`PINATTR PinName ${terminal}`);
    lines.push(`PINATTR SpiceOrder ${index + 1}`);
  });
  return lines.join("\n") + "\n";
}

function parse(output: string, pattern: RegExp): number | null {
  const match = output.match(pattern);
  if (!match) return null;
  const value = Number.parseFloat(match[1]);
  return Number.isFinite(value) ? value : null;
}

/**
 * The conformance deck.
 *
 * Four DC operating points, which is all a reference needs and all it can
 * honestly be asked for. Two of them differ only in the input voltage and two
 * only in the load current, so each regulation term is measured as the
 * derivative the datasheet says it is.
 */
function deck(subckt: string, name: string, corner: number, anchor: number, probeCurrent: number): string {
  return [
    `* Forge conformance deck for ${name}, corner ${corner}`,
    subckt,
    `Xa in_a out_a 0 ${name} CORNER=${corner}`,
    `Xb in_b out_b 0 ${name} CORNER=${corner}`,
    `Xc in_c out_c 0 ${name} CORNER=${corner}`,
    `Vin_a in_a 0 DC ${toSpice(anchor)}`,
    `Vin_b in_b 0 DC ${toSpice(anchor + 1)}`,
    `Vin_c in_c 0 DC ${toSpice(anchor)}`,
    // A and B are unloaded and differ only in supply: the line slope.
    // C differs from A only by a load current: the load slope.
    `Iload out_c 0 DC ${toSpice(probeCurrent)}`,
    ".control",
    "op",
    // THE SIMULATOR DOES THE SUBTRACTION, not us.
    //
    // Both regulation terms are differences between two nearly equal voltages:
    // a 1 ppm/V slope moves a 2.5 V output by 2.5 µV. Printing the two voltages
    // and subtracting them here throws away every digit the answer lives in -
    // measured, a stated 1.0 ppm/V came back as 0.8 ppm/V, a 20% error that is
    // entirely the printed precision. Differencing inside the simulator keeps
    // the full relative precision of the result.
    "let dline = v(out_b)-v(out_a)",
    "let dload = v(out_a)-v(out_c)",
    "print v(out_a)",
    "print dline",
    "print dload",
    "print i(Vin_a)",
    ".endc",
    ".end",
    ""
  ].join("\n");
}

/** What a generic DC rig can measure on a reference, and nothing else. */
const MEASURABLE: ModelParameter[] = ["outputVoltage", "lineRegulation", "loadRegulation", "quiescentCurrent"];

/**
 * Runs the reference model and compares it against the values it was built from.
 *
 * Never throws. A missing simulator reports every check `unverifiable` with the
 * reason, because a product that cannot verify is a worse product, not a broken
 * one.
 */
export async function verifyReference(
  subckt: string,
  block: ModelBlock,
  partNumber: string,
  corners: Array<"typ" | "min" | "max">
): Promise<ConformanceReport> {
  const name = spiceName(partNumber);
  const checks: Check[] = [];
  const directory = await mkdtemp(join(tmpdir(), "forge-spice-ref-"));
  const anchor = anchorSupply(block);
  /** 1 mA, which is inside every load range this class states. */
  const probeCurrent = 1e-3;
  let simulatorMissing = false;

  const unverifiable = (parameter: ModelParameter, corner: "typ" | "min" | "max", reason: string) => {
    if (!usableAt(block, parameter, corners)) return;
    const expected = valueAt(block, parameter, corner);
    if (expected !== null) checks.push({ parameter, corner, expected, measured: null, verdict: "unverifiable", reason, errorPct: null });
  };

  try {
    for (const corner of corners) {
      const nominal = valueAt(block, "outputVoltage", corner);
      if (nominal === null) continue;
      // A PROBE POINT IS NOT AN OPERATING POINT.
      //
      // This refused to simulate anything without a stated supply, and scored
      // two references 0 of 9 with clean models. Only the LINE regulation
      // depends on where the input sits; the output voltage, the load slope and
      // the quiescent current do not. And where no supply was read the emitter
      // has already left the line term OUT, so the model's output cannot depend
      // on the input at all: any probe voltage gives the same answer, which is
      // what makes picking one a measurement detail rather than a modelling
      // choice. The line regulation is reported unverifiable in that case,
      // because the model genuinely does not contain it.
      const probeInput = anchor ?? nominal + 1;
      const file = join(directory, `${name}-${corner}.cir`);
      await writeFile(file, deck(subckt, name, CORNER_INDEX[corner], probeInput, probeCurrent), "utf8");
      const { stdout, ok } = await runNgspice(file);
      if (!ok) {
        simulatorMissing = true;
        for (const parameter of MEASURABLE) unverifiable(parameter, corner, "ngspice is not available on this host");
        continue;
      }

      const outA = parse(stdout, /v\(out_a\)\s*=\s*([-\d.eE+]+)/);
      const dLine = parse(stdout, /\bdline\s*=\s*([-\d.eE+]+)/);
      const dLoad = parse(stdout, /\bdload\s*=\s*([-\d.eE+]+)/);
      const supplyCurrent = parse(stdout, /i\(vin_a\)\s*=\s*([-\d.eE+]+)/);

      const measured: Partial<Record<ModelParameter, number | null>> = {
        outputVoltage: outA,
        // Both regulation terms come back in the units the record holds them
        // in: a FRACTION of the nominal output, per volt and per amp.
        //
        // The line slope is only measurable where the model CONTAINS it, which
        // needs the anchor. Measuring it without one would read zero and report
        // the model as disagreeing with a datasheet it never claimed to match.
        lineRegulation: anchor !== null && outA !== null && dLine !== null && outA !== 0 ? dLine / outA : null,
        loadRegulation: outA !== null && dLoad !== null && outA !== 0 ? dLoad / outA / probeCurrent : null,
        quiescentCurrent: supplyCurrent === null ? null : Math.abs(supplyCurrent)
      };

      for (const parameter of MEASURABLE) {
        // The one definition of usable, which is what the emitter asks. See the
        // same guard in `verify.ts`: a parameter with a value at this corner and
        // not at every corner produces no element, and measuring it anyway
        // reports the model as disagreeing with its own datasheet.
        if (!usableAt(block, parameter, corners)) continue;
        const expected = valueAt(block, parameter, corner);
        if (expected === null) continue;
        const value = measured[parameter] ?? null;
        if (value === null) {
          unverifiable(
            parameter,
            corner,
            parameter === "lineRegulation" && anchor === null
              ? "the datasheet states no supply voltage, so the line-regulation slope has no anchor and is not in the model"
              : "the simulation produced no value for this measurement"
          );
          continue;
        }
        const errorPct = expected === 0 ? (value === 0 ? 0 : 100) : Math.abs((value - expected) / expected) * 100;
        checks.push({
          parameter,
          corner,
          expected,
          measured: value,
          verdict: errorPct <= TOLERANCE_PCT ? "pass" : "fail",
          reason: errorPct <= TOLERANCE_PCT ? undefined : `measured ${value.toPrecision(4)} against a stated ${expected.toPrecision(4)}`,
          errorPct
        });
      }

      // Temperature is not a node in this netlist, so the drift is reported
      // rather than measured badly. Same rule as the amplifier's slew rate.
      unverifiable("outputDrift", corner, "temperature is not a node in this model, so its drift cannot be simulated");
    }
  } finally {
    await rm(directory, { recursive: true, force: true }).catch(() => {});
  }

  return { checks, simulatorMissing };
}
